### ISSUE TITLE
Allow s3sync to be called with command line arguments

### ISSUE THREAD

**Issue by chrisspen** [k3karthic/S3Sync#1]
Requiring a hard-coded configuration file makes this tool very difficult to use in many cases where you need to operate on multiple accounts with multiple buckets. Allowing these parameters to be passed as arguments would be simpler than parsing a configuration file, and make the tool much more flexible.

I stumbled across this project looking for a replacement to the Ruby tool [s3sync](https://github.com/ms4720/s3sync), which generally works well, but has intermittent maintenance, doesn't work well with my Python toolset, and is very difficult to install on Ubuntu. Unfortunately, I can't use your package due to these limitations with a hard-coded config file.

**Comment by k3karthic** [comment]
Hi chrisspen,

Thanks for the feedback, this project has also not seen maintenance in quite some time as the [AWS Cli](http://aws.amazon.com/cli/) has matured and has excellent S3 sync capabilities and incidentally is also written in Python.

It has support for multiple accounts and many more features. I have used it professionally and it can handle large datasets efficiently. The only requirement is that the time on your system must be synced for it to work properly.

[AWS S3 Cli](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html)

**Comment by chrisspen** [comment]
You're right. Also, s3cmd works well too.
